### ISSUE TITLE
access spec declaration methods from modules

### ISSUE THREAD

**Issue by leafo** [Olivine-Labs/busted#320]
Sometimes I make helper modules with utility functions for declaring tests that are very similar:

```lua
-- test_helpers.lua
local function make_test(a, b)
  return it("should check " .. a .. " same as " .. b, function()
    assert.same(a, b)
  end)
end
return {
  make_test = make_test
}
```

And then use them like this: 
```lua
local make_test = require("test_helpers").make_test
return describe("things", function()
  make_test(1, 2)
  make_test(4, 4)
end)
```

In busted 2.0 this is no longer possible since the spec declaration methods like `it` and `describe` are only available within the `setfenv` functions.

One possible solution would be to make spec methods importable from the busted module: 

```lua
-- test_helpers.lua
local it = require("busted").it

local function()
  it("should do something", ...)
end
```

**Comment by DorianGray** [comment]
This duplicates https://github.com/Olivine-Labs/busted/issues/319

**Comment by DorianGray** [comment]
I made this the main issue since the explanation is better.

To solve this, we need to refactor init.lua to have one file per function, or set of functions. One would then require a specific function in to use it outside of files directly executed by the test runner.

IE::
local it = require 'busted.it'

Because we would have already required busted.it in busted init, the require inside of this external file would be fed the same instances of the functions that the init process is, therefore allowing them to operate on the active instance of busted.

**Comment by o-lim** [comment]
I took a crack at this in PR #322.  Let me know what you think.
