### ISSUE TITLE
A way to switch LUA/LUAJIT from busted cli

### ISSUE THREAD

**Issue by kureikain** [Olivine-Labs/busted#330]
Hey,

I'm new to LUAJIT and I found that busted cli have `#!usr/bin/env lua` so it will not use LUAJIT or a way to switch. Right now I'm doing the symbolic link `lua->luajit` but I feel it is wrong and not sure that's the right way to do it.

I think it will be nice if we can do something like this:

```
LUA=luajit busted spec.lua
```

**Comment by DorianGray** [comment]
So.... this is complicated.

Certain modules that are installable from luarocks and that are compiled for lua 5.1/2 do not work in luajit. You get these fun core dump errors when you try to load them. Errors around memory allocations and tracking.

This is compounded by system level differences with shell/bash scripts that caused us to remove this feature in the first place.

...In other words, you need to set up a separate luarocks environment that uses luajit instead of lua to get this to work properly. This can be accomplished in an automated way by using https://github.com/torch/torch7 which has a modified version of luarocks.

**Comment by DorianGray** [comment]
If you want more information, there is plenty in some of our other closed issues here.

**Comment by jcupitt** [comment]
It looks like the torch luarocks repo has moved. I think it's now at:

https://github.com/torch/luajit-rocks

**Comment by d9k** [comment]
BTW, there is a bug in luajit-rocks:

At generated `site_config.lua` `site_config.LUAROCKS_EXTERNAL_DEPS_SUBDIRS` and `site_config.LUAROCKS_RUNTIME_EXTERNAL_DEPS_SUBDIRS` are missing: (see https://github.com/daurnimator/lua-http/issues/39#issuecomment-248057342)

**Comment by kapouer** [comment]
`luajit /usr/bin/buster spec/*.lua` ?
