### ISSUE TITLE
Make module reloading opt-in rather than opt-out...

### ISSUE THREAD

**Issue by jszakmeister** [Olivine-Labs/busted#372]
I'm a bit worried about user experience here.  Mike Pall said that the [ffi module cannot be reload](https://www.freelists.org/post/luajit/Assertion-error,5), and I think he's right in that C-based modules may have a number of issues on this front too.

So rather than leave folks to tracking down obscure issues, perhaps it would be better to opt-in for the test isolation, especially since it's clear it doesn't work everywhere?

**Comment by ajacksified** [comment]
Hmm, this is a tough one. I would think that more people will have issues with modules *not* reloading than will have issues *with* reloading, but on the other hand, when you do have issues, they're hard to track down. Thoughts, anyone else?

**Comment by jszakmeister** [comment]
@ajacksified I see it the other way around.  Your modules don't normally reload in a Lua app, why would you expect them to in a Lua unit tester?  I believe in regular Lua would have issues with some of the C modules being reloaded.  It seems more like a hack than a supported feature of the language.

Separate processes would probably be the best way to get isolation, but Windows is painful on that front.  Not only do you not have fork(), the process startup time is 100x to 1000x times slower than Linux. :-(

**Comment by mpeterv** [comment]
I'm not sure how sandboxing is done currently, I assume it is implemented in [busted/context.lua](https://github.com/Olivine-Labs/busted/blob/f186d640f05d8d84de576225bac1c7ea4b37350d/busted/context.lua) with `save` function called before loading a file and `restore` after? Is there any environment assigned to main chunks of files, or does it break if the file sets globals which are used in `restore` function (e.g. `_G` = nil)? Does removing lines 20-22 fix the issue?

**Comment by mpeterv** [comment]
Also, I think I agree with @jszakmeister - if you want to test if _your_ module breaks because of reloading, that's easy to do explicitly; if a module you use breaks on reload (like `ffi`), it shouldn't be your problem; and if a module you use breaks because your module messes up with it, reloading it only hides the issue.

**Comment by o-lim** [comment]
From the perspective of using a module in a Lua app, you would not expect any module to be reloaded.  However, when unit testing you want to be able start each test "clean" and not impacted by the success or failure of a previous test.  Since many Lua modules will modify their internal state, the only way to achieve test isolation is to reload the module being tested or run each test in a separate process.  Running each test in either scenario comes with it's own set of hurdles to overcome.  

Busted runs everything in one process, sandboxing each test as much as possible.  In the case of reloading modules, it only does this for each test file, not each individual test withing a file.  It's true that you would not expect your Lua modules to be reloaded between tests within a file.  However, from file to file, it is not unreasonable to expect that your unit test environment is "clean" at start of the test file.  You certainly don't want `test1_spec.lua` affecting `test2_spec.lua`, expecting some level of isolation.

I don't think it's an issue of testing if your module breaks because of reloading, but rather what is the best way to get test isolation.  Should the test writer be responsible for unloading his module at teardown, if necessary, so as to not impact other test files? Or should the unit test environment do that sort of thing for you?  Or should there be a command-line flag that enables/disables this feature?
Or maybe a special API function that save/restore the current environment, to be invoked by the test writer in `setup`/`teardown`?

**Comment by jszakmeister** [comment]
> However, from file to file, it is not unreasonable to expect that your unit test environment is "clean" at start of the test file. You certainly don't want test1_spec.lua affecting test2_spec.lua, expecting some level of isolation.

It is when you understand processes and things *should* work.  Reloading modules is unexpected here.

Don't get me wrong, I think isolation is a good thing.  I just think the bit should be flipped the other way.  I spent a *considerable* number of hours tracking down what was happening.  It was definitely unexpected behavior.

> I don't think it's an issue of testing if your module breaks because of reloading, but rather what is the best way to get test isolation.

I don't think you can disregard the fact that there are modules that break because of reloading though.

> Should the test writer be responsible for unloading his module at teardown, if necessary, so as to not impact other test files? Or should the unit test environment do that sort of thing for you? Or should there be a command-line flag that enables/disables this feature?

In my experience, no other framework I've used has attempted to provide this kind of isolation in process--precisely because of the problems that come with it.  I'm not saying Busted should remove it, but I think it should be an opt-in rather than an opt-out feature set.  In the many test frameworks I've used, it was up to the test writer to help provide this.  While that has its downsides, it does have the upside that you are in full control.

I don't want to come across as passionately caring about this issue--I don't.  I know enough now to make it work for me.  But I like to think of others, and considering how off guard it caught me, I suspect others will have similar issues.  And the result in LuaJIT was really nasty--assertion errors causing things to forcefully terminate.  That's pretty daunting for an inexperienced person to work through.

Just in case I wasn't clear, I'd vote for a command line flag to enable the behavior (`--enable-module-clearing` or the like).

**Comment by DorianGray** [comment]
We like passion here. Also, we're all working towards the best decision, and I believe that more ideas will help us reach it. Please continue contributing =)

We can also provide a way to register libraries in the global namespace that does not get cleaned up between tests, as well as a way to register libraries for cleanup. Implementing a control syntax in the "file" scope might be useful.

Maybe something like...

local ffi = require 'ffi'
isolate()

Where everything past isolate has automatic cleanup, and everything before has unmitigated access to the real _G. Because of the 2 pass nature of the test runner I believe this is possible. We can then add a new cli option for isolate that sets the default isolate state, as well as a way to turn isolation off... like combine() or desegregate() or unify()

**Comment by o-lim** [comment]
@DorianGray: Just expanding on your thoughts, what about something like the following, where `insulate` would automatically restore the global environment, and `elevate` would allow the global environment to be updated.
```lua
-- test1_spec.lua
assert(package.loaded.ffi == nil)
assert(_G.file_global == nil)
assert(_G.elevated_global_var == nil)

file_global = 'this global is still only visible in this file'

elevate(function()
  local ffi = require 'ffi'
  _G.elevated_global_var = 'elevate this global to the parent environment'
  block_global = 'this global is still only visible in the current context'
  describe('Tests', function()
  ...
  end)
end)

assert(block_global == nil)
assert(file_global)
assert(_G.file_global == nil)
assert(_G.elevated_global_var)
assert(package.loaded.ffi)
```
```lua
-- in test2_spec.lua
assert(file_global == nil)
assert(elevated_global_var)
assert(package.loaded.ffi)

describe('Tests', function()
...
end)
```
and to go the other way
```lua
assert(package.loaded.socket == nil)
assert(_G.insulated_global_var == nil)

insulate(function()
  local socket = require 'socket'
  _G.insulated_global_var = 'this global does not get elevated to the parent environment'
  describe('Tests', function()
  ...
  end)
end)

assert(_G.insulated_global_var == nil)
assert(package.loaded.socket == nil)
```
You can even nest `insulate` and `elevate` inside of each other like so
```lua
elevate(function()
  local ffi = require 'ffi'
  ...

  insulate(function()
    describe('Tests', function()
    ...
    end)
  end)
end)
```
This way you have full control of the level of isolation you want to achieve for your tests.  Calling `elevate` at the root of a file will promote any requires and global variables (created with using `_G`) to the root environment, which will then spillover into subsequent tests.

Busted can default to isolation mode (or elevated mode), with a command-line flag to change the default behavior.

I wasn't sure what to name these functions.  I was thinking `insulate`/`isolate`/`protect` and `elevate`/`boost`/`uplift`/`promote`.

**Comment by o-lim** [comment]
I guess what I'm describing would be the same is having two special `describe` blocks, one to isolate/insulate a group of tests, and the other to basically do the opposite. (e.g. `describe_insulated` and `describe_elevated`)

**Comment by DorianGray** [comment]
I like insulate...maybe uncover for the second? I like the inclusion of function scoping into this.

**Comment by DorianGray** [comment]
@jszakmeister That work?
