### ISSUE TITLE
assert.has.no.errors() throws away tracebacks

### ISSUE THREAD

**Issue by Alloyed** [Olivine-Labs/busted#381]
When running busted in verbose mode, an error caught in a assert.has.no.errors() block will discard the useful part of the traceback, returning only the direct error message. Example:
```
./spec/let_spec.lua:14: Expected no error, but caught:
(string) './core/gen.lua:47: attempt to index local 'expr' (a nil value)'

stack traceback:
	./spec/let_spec.lua:14: in function <./spec/let_spec.lua:13>
```
When the same code is run outside of an assert I get this back, instead:
```
./core/gen.lua:47: attempt to index local 'expr' (a nil value)

stack traceback:
	./core/gen.lua:47: in function 'gen'
	./core/builtins.lua:15: in function 'defval'
	./core/builtins.lua:57: in function <./core/builtins.lua:52>
	(...tail calls...)
	./core/gen.lua:52: in function 'gen'
	./core/gen.lua:42: in function 'exprlist'
	./core/gen.lua:50: in function 'gen'
	./spec/let_spec.lua:6: in function 'run'
	./spec/let_spec.lua:14: in function <./spec/let_spec.lua:13>
	...
```

**Comment by o-lim** [comment]
I don't see a problem here.  It looks like everything is behaving as it should.  You have an assert hat failed at `./spec/let_spec.lua:14`, and that is what is reported to you at the beginning of the traceback.  Your assert is `assert.has.no.errors` which failed, and was caught by busted.  It doesn't look like busted is discarding anything.  The traceback you are interested in is just not available to busted because it was caught by the assert.

The traceback you are getting is consistent with every other traceback resulting from an assert.  If you put `assert.is_true(false)` at `./spec/let_spec.lua:14`, you would get the exact same traceback.  The traceback is telling you where the `assert` failed, it's not going give you any information as to why it failed.

When you remove the assert, you get the full trackback because an unexpected error occurred while running your test and busted is reporting the traceback of that error.  When you wrap it with an `assert.has.no.errors`, you are telling busted to verify that the function does not throw an error.  When this check fails, your test has failed, so busted reports the call-site of the failure, which occurred at `./spec/let_spec:14`.

I understand your dilemma, but I it looks like everything is behaving as I would expected.  The original trackback is simple not available due to the nature of `assert.has.no.errors`.  The assert caches any error and compares it to any expected error object, then throws a new error if they do not match.  I don't think there is any way to preserve the original stack trace in Lua.  Perhaps one option is to append the original stack trace to the error message reported by `assert.has.no.errors`, which would be a change to luassert, not busted.
