### ISSUE TITLE
Please use the HTTPS repo url in the rockspec file

### ISSUE THREAD

**Issue by OptiverTimAll** [Olivine-Labs/busted#405]
I'm trying to build NeoVim, which depends on busted. It installs busted by running the following command:

    luarocks build https://raw.githubusercontent.com/Olivine-Labs/busted/master/busted-scm-0.rockspec

The command successfully obtains the `.rockspec` file via our HTTP proxy, but then it tries to clone the listed repo which uses a `git://` URL and therefore fails. If you could update the `.rockspec` file to mention https://github.com/Olivine-Labs/busted.git instead of the `git://` URL, I (and many other people behind restrictive firewalls) would be very appreciative.

**Comment by o-lim** [comment]
Sorry, looks like luarocks does not support https with git.  Couldn't use use the rc rockspec instead?

**Comment by o-lim** [comment]
Why can't you update NeoVim to install busted via `luarocks install busted`?  I believe the `busted-2.0` rockspec uses https, which would solve your problem.  Or you could just manually clone and install busted yourself.
```
git clone https://github.com/Olivine-Labs/busted.git
cd busted
sudo luarocks make busted-scm-0.rockspec
```
You should probably be using the latest released version of busted, rather than cloning the latest master branch.  If there is a feature you need that is not in busted-2.0-rc7, then maybe that means it's about time to release busted-2.0-rc8?

**Comment by jszakmeister** [comment]
> If there is a feature you need that is not in busted-2.0-rc7, then maybe that means it's about time to release busted-2.0-rc8?

Yes, that's exactly the case.  There have been a series of little things that keep us from using the latest released version.  The biggest thing at the moment though is some of the enhanced reporting that has been added.

> Or you could just manually clone and install busted yourself.

We try to keep things easy for contributors, but coordinating something like this would be a real PITA.  OTOH, your current scm spec is broken--it does not do what you intend.

I did get a patch into luarocks (keplerproject/luarocks#350) to fix the issue, but it's probably best to stick to `git+http` for now, as any luarocks that doesn't support `git+https` would fail.

**Comment by o-lim** [comment]
Sounds like the ideal solution might be to get busted-2.0-rc8.  Then you could just use `luarocks install busted`.  In general, I would prefer this over cloning the latest master branch.

I changed the scm rockspec back to use the git protocol since the git+https wasn't supported.

@DorianGray any chances for an rc8 release some time soon?

**Comment by ajacksified** [comment]
rc8 released.

**Comment by o-lim** [comment]
Minor issue with rc8, but not a big deal.  Looks like the version string in rc8 was not updated.  The version string in `core.lua` still says "2.0-rc6-0".

**Comment by o-lim** [comment]
@OptiverTimAll looks like newvim has been updated to use busted-2.0.rc8, so you should no longer have issues with using https to get busted.
