### ISSUE TITLE
Cannot install busted 2.0.rc8 via luarocks

### ISSUE THREAD

**Issue by o-lim** [Olivine-Labs/busted#412]
Luarocks give an error when trying to install busted-2.0.rc8, giving the following error
> Error: Failed installing dependency: http://luarocks.org/repositories/rocks/mediator_lua-1.1.1-0.rockspec - Error fetching file: Failed downloading https://github.com/Olivine-Labs/mediator_lua/archive/v1.1.1.tar.gz - HTTP/1.1 404 Not Found

Looks like it cannot get mediator v1.1.1 because it does not exist.  The latest release of mediator is v1.1.0, but the previous version was v1.1.  It looks like there was a typo somewhere, either in the mediator release version number or in the busted-2.0.rc8 rockspec.

**Comment by o-lim** [comment]
Closing since it duplicates #411

**Comment by hoangandrew** [comment]
I have the same problem: unable to install busted:
$> luarocks.bat install busted

I searched all over the internet for solution but can not find any.  Finally, I found the root cause.
To fix this issue, I open file luarocks.bat and remove line <call "C:\Program Files (x86)\Microsoft Visual Studio 8\VC\bin\vcvars32.bat">.  Then installation busted goes smooth.

Problem is the luarocks.bat used Visual studio compiler and it not good.  We have to use mingW32-gcc. 

Hope I can help someone to get stuck as I did.  Follow steps below to install busted:
- Download and run https://osdn.net/projects/mingw/downloads/68260/mingw-get-setup.exe/
- Install Luarocks: Download http://luarocks.github.io/luarocks/releases/luarocks-3.1.2-win32.zip
- Unzip
- Open command line console as Administrator
- From a command line run install.bat /F /L
