### ISSUE TITLE
stack overflow and has_error behaviour

### ISSUE THREAD

**Issue by thibaultCha** [Olivine-Labs/busted#425]
Since `2.0.rc9-0` 2 days ago, we are experiencing some issues we weren't seeing before on our tests. This is observable on our [travis tests](https://travis-ci.org/Mashape/kong/pull_requests) (ignore tests before 3 days ago: they fail for valid reasons, but none of the following new errors).

I am seeing 2 kinds of errors:

- a stack overflow, observable [here](https://travis-ci.org/Mashape/kong/builds/64752205) and in all the travis tests of those last 2 days.
- `assert.has_error()` thinks the thrown error doesn't match, but it actually does.

All those tests were working 3 days ago, and they haven't been changed in the last few months. 

However, I tried reverting to `2.0.rc8-0` but without success. I am thinking maybe one of the busted dependencies is causing this and got bumped in both rc9 and rc8?

I also tried to reproduce the stack overflow error, without success. The error apparently comes from using **spies and stubs** on objects. Sometimes, the error trace comes from other files like:

```
/usr/local/share/lua/5.1/luassert/util.lua:37: stack overflow
```

Could it be possible that a breaking change was introduced recently?

**Comment by ajacksified** [comment]
luassert was updated along with busted recently - if you downgrade to rc8, and downgrade luassert to 1.7.6, does your problem go away?

**Comment by thibaultCha** [comment]
Yes, as I thought, `'luassert >= 1.7.6-0'` also breaks it for rc7, which is why downgrading didn't fix it in the first place.

With luassert 1.7.6 and busted rc8/rc9, the both issues go away.

**Comment by o-lim** [comment]
I ran into the same issue the other day.  I'll submit a PR to luassert to fix this today or tomorrow.

**Comment by o-lim** [comment]
Just submitted a PR to luassert (olivine-labs/luassert#109) that fixes this issue.  @thibaultCha can you give it a try?

**Comment by ajacksified** [comment]
If latest luassert master works for you, I'll cut an rc10 release.

**Comment by thibaultCha** [comment]
Using luassert master, I do not see the stack overflow error anymore so that's cool, but the `has_error` not recognising the error is still there.

**Comment by o-lim** [comment]
Looks like the errors you are getting with `has_error` are because the thrown error is not equal to the expected error.  If they do not match exactly `has_error` will fail.  This was the original behavior of `has_error`.  However, it looks like it was changed at some point to find a sub-string in order to deal with the `filename:line: ` prefix, which was why your tests were passing before.  I restored the original behavior of `has_error` to match the entire string in v1.7.7, and that is why your tests are failing now.  I submitted a PR to luassert (olivine-labs/luassert#113) to add an `error_matches` assertion, that would match an error with an expected Lua pattern or sub-string.  Can you try out this PR, replacing `has_error` with `error_matches`?

The `error_matches` assertion has the form:
```
assert.error_matches(pattern, func [, init [, plain]])
```

**Comment by o-lim** [comment]
@thibaultCha I updated PR Olivine-Labs/luassert#113 to take a function as the first argument to match `has_error`, so all you would need to do is replace `has_error` with `error_matches` (or `does_error_match` if you prefer).  Could you give this a try?

**Comment by thibaultCha** [comment]
That sounds good @o-lim!

**Comment by o-lim** [comment]
@ajacksified since the bugs have been fixed in `luassert`, did you want to cut an rc10 release soon?

**Comment by ajacksified** [comment]
@o-lim yup, will cut tonight or tomorrow.
