### ISSUE TITLE
Segmentation fault with LuaJIT

### ISSUE THREAD

**Issue by thefosk** [Olivine-Labs/busted#426]
I am experiencing the following error:

```
/home/travis/build.sh: line 41:  9831 Segmentation fault      
busted -o spec/busted-print.lua --coverage spec/ spec/integration/cli/
The command "busted -o spec/busted-print.lua --coverage spec/ spec/integration/cli/" exited with 139.
```

Using LuaJIT `2.0.4` and busted `2.0.rc9-0`.

**Comment by o-lim** [comment]
Looks like the entire test suite successfully ran, but a segmentation fault occurs on exit.  Maybe this has something to do with the garbage collection that is done on exit for Lua 5.1.  Since LuaJIT 2.0 and later supports the Lua 5.2 style `os.exit(status [, close])`, the garbage collection workaround for Lua 5.1 is not necessary.  I submitted PR #428 to bypass the manual garbage collection step if LuaJIT 2.0 or later is detected.  Maybe this will fix the segmentation fault you are seeing on exit.

**Comment by o-lim** [comment]
@thefosk are you able to reproduce this on your local machine?  I've seen this same error in my pull requests for `luassert`, but I cannot reproduce the problem on any of my machines (Ubuntu 12.04 LTS and CentOS/RedHat 6.5).  For some reason I can only see the problem when it runs in travis.

**Comment by thefosk** [comment]
I confirm that the patch has fixed this problem

**Comment by DorianGray** [comment]
We'll get a new release out soon.

**Comment by thefosk** [comment]
The problem seems to be occurring again: https://travis-ci.org/Mashape/kong/builds/70464238#L1091

**Comment by o-lim** [comment]
Since this problem only occurs on exit, I'm not sure this can be fixed with changes to busted.  It looks more like a problem with LuaJIT and how it handles garbage collection and/or how it closes the Lua state.

**Comment by chrox** [comment]
And exactly the same problem here: https://travis-ci.org/koreader/koreader/builds/83900156#L7901

with LuaJIT 2.1.0-beta1 and busted-2.0.rc10-0.

**Comment by raingloom** [comment]
Exact same problem for me
https://travis-ci.org/raingloom/raincoat/jobs/88841464#L659
