### ISSUE TITLE
require isolation part 2?

### ISSUE THREAD

**Issue by karlp** [Olivine-Labs/busted#433]
I had originally filed https://github.com/Olivine-Labs/busted/issues/62 and got workaroudns with 

```lua
my_uci = require("uci")
my_uci.set_confdir(blah)
package.preload['uci'] = function() return my_uci end
```

All well and good.  I'm now using busted 2.0rc9 and it doesn't work anymore, depending on the order of execution I get a different version of the uci module loaded.  No amount of playing with isolate/expose has helped.  I've tried to replace the UCI module with a stub to demonstrate the issue, but however I've made my stub doesn't exhibit the same behaviour.

How is one _meant_ to reconfigure a module that the code under test will require()?  I can't (won't) change the code under test

I've put a sample project, fwiw, at https://github.com/karlp/busted-busted-isolation

**Comment by o-lim** [comment]
I'm not quite sure what you are trying to do.  According to #62, you wanted to reload `uci` for each spec file.  However, in your workaround, it looks like you are always returning the same `uci` module, which means it is never reloaded.

busted 2.0rc9 will, by default, isolate each spec file from every other spec file.  So when you `require 'uci'` in one spec file, and then `require 'uci'` another spec file, each spec file will get a different copy of `uci` because it was reloaded for each spec file.  I believe this is the isolation you were looking for in #62.  If you use `insulate`, then everything within the `isolate` block is isolated such that any changes to `_G` or `package.loaded` are undone at the end of the block.  The `expose` block does the opposite, it retains changes in `_G` and `package.loaded` propagating the changes to the outer blocks.  If you use `expose` at the top level of a spec file, then all changes to `_G` and `package.loaded` are propagated to all subsequent spec files.

From your workaround, it looks like you want `uci` to be loaded only once for all of your spec files.  In this case you can use the `--helper` flag to pass a `helper.lua` file that does `require 'uci'`, or `require 'uci'` inside of an `expose` block in your first spec file, or use the `--no-auto-insulate` flag.

It looks like the `uci` Lua module does not like to be reloaded.  So it is not `insulate` friendly.  This is also true for the `ffi` module in LuaJIT, and probably many Lua modules written in C.

In your example, your first test case looks like it is running correctly, except that `uci` doesn't load the local config file, yet the `confdir` was updated.  Seems like something is going on internally in `uci` that is reading the wrong file or not reading the new file.  With case 2, a new `uci` table is loaded for the system spec, but it is not using the default `confdir`.  It somehow retained information from the old `uci` table.  Again, this looks like something `uci` is doing internally.  Maybe it is storing the information in a shared library (i.e. libuci.so), but the library doesn't get unloaded and reloaded when `uci.so` gets reloaded by Lua?  In this case, I don't think `uci` can be reloaded and still be expected to operate correctly.  This would mean you cannot achieve test isolation with `uci`, you would have to leak `uci` across all of your tests.

If everything was in pure Lua, I don't think you would have a problem.  This is probably why your stub behaves differently.

One thing you can try is to run the garbage collector several times between spec files to see if Lua can unload `uci` properly.  Basically add a dummy `describe` or `it` block at the end of the spec file, outside of the `insulate` block, and do a bunch of garbage collections in that dummy block.  Maybe Lua will unload the `uci` shared libraries when it does garbage collection on `uci`.

**Comment by karlp** [comment]
I'd say I probably _want_ isolation, and the old preload hacking was to work around when someone (possibly me, way back then) worked out that the uci library (yes, it is a lua binding to a C library) didn't like being reloaded. 

If I try to "expose" the require of uci, how can I control that it is first?  I guess I should use something like the helpers here https://github.com/jszakmeister/neovim/commit/3605edca0d8618a8f3fba211d5485608c1cd39c2 and have those set the directory?

I think I'll just toss the tests honestly, it's been a massive time sink and updating has just sucked in more time.

**Comment by o-lim** [comment]
If you want to automatically have the directory reset to some default for every spec file, you can add a setup/teardown to each spec file using the helper.
```lua
-- helper.lua
local busted = require 'busted'
local uci = require 'uci'
local default_confdir = ...

local function file_setup()
  uci.set_confdir(default_confdir)  -- cleanup at start of spec file
end

local function file_teardown()
  uci.set_confdir(default_confdir)  -- or cleanup at end of spec file
end

busted.subscribe({'file', 'start'}, file_setup)
busted.subscribe({'file', 'end'}, file_teardown)
```
Then you can keep the code in your `describe` `setup` to set the directory for your test.  This can be a way to _fabricate_ your own isolation.  It's too bad that Lua doesn't really allow for easy module unloading.

**Comment by karlp** [comment]
Thanks for the ideas.  I'm restructuring things a lot to try and simplify what's even being tested so I don't need to rely on things this much.  a lot of it seems to come down to the uci library not really respecting repeated calls to set_confdir().
