### ISSUE TITLE
Remove luasocket dependency

### ISSUE THREAD

**Issue by daurnimator** [Olivine-Labs/busted#472]
I'm trying to use busted to test code that does different things depending on whether luasocket is installed or not. The luasocket dependency is quite large; and only used for `socket.gettime()` (which returns the current time with microsecond precision)

**Comment by DorianGray** [comment]
What do you suggest we replace it with? We need millisecond precision for test runtimes.

**Comment by daurnimator** [comment]
> We need millisecond precision for test runtimes.

What's wrong with `os.clock()`? That actual provides cpu time (rather than wall clock time)

Wall clock time is problematic in the first place: any changes to the local clock (e.g. if you're running an ntp daemon) will result in incorrect times with the current style. If you don't want CPU time for some reason, you should at least move to a monotonic clock.

**Comment by benbarbour** [comment]
We also just discovered this dependency because it started causing problems for some code we have that depends on an older version of luasocket. We would love to to get rid of the dependency as well.

**Comment by DorianGray** [comment]
CPU time, unfortunately, isn't always useful. Applications that do a lot of IO(specifically async io) don't report correct times because most of the test time is spent in the kernel, not in the test.

When we originally switched from os.clock to luasocket, an effort was made to find a library that only provided reliable time but nothing was found. If we can find/create a library that uses RDTSC, that would be ideal. Best case, it should also support ARM and MIPS.

**Comment by daurnimator** [comment]
> When we originally switched from os.clock to luasocket, an effort was made to find a library that only provided reliable time but nothing was found. If we can find/create a library that uses RDTSC, that would be ideal. Best case, it should also support ARM and MIPS.

A library that exposes a single function `monotime` would be simple. e.g. just grab the code from https://github.com/wahern/cqueues/blob/master/src/cqueues.c#L118
