### ISSUE TITLE
Using from automake

### ISSUE THREAD

**Issue by daurnimator** [Olivine-Labs/busted#487]
How should you use busted from automake?
https://www.gnu.org/software/automake/manual/html_node/Overview-of-Custom-Test-Drivers-Support.html#Overview-of-Custom-Test-Drivers-Support

**Comment by djerius** [comment]
Here's effectively what I do. (I've simplified things, so the following might have some typos)

In `configure.ac`:
```
dnl AX_PROG_LUA is from autoconf archive
dnl https://www.gnu.org/software/autoconf-archive/ax_lua.html
AX_PROG_LUA([5.1],[5.2],[],[AC_MSG_ERROR([no Lua??])])

dnl make sure the busted executable is in our path
AC_PATH_PROG(BUSTED,busted)

dnl and make sure that we can load the busted module
AS_IF([$LUA -l busted -e 'return'],[],[AC_MSG_ERROR([can't load busted module])])
```

I use `automake`'s [parallel test harness](https://www.gnu.org/software/automake/manual/automake.html#Parallel-Test-Harness). In the test directory's `Makefile.am` (note this layout is for non-recursive makefiles where the test directory's `Makefile.am` is being `include`ed by the top level `Makefile.am`) :

```
TEST_EXTENSIONS += .lua
LUA_LOG_COMPILER = $(BUSTED) -o TAP -m '$(top_srcdir)/%D%/?.lua;$(top_srcdir)/lua/?.lua;$$LUA_PATH;;'

TESTS += %D%/test.lua
EXTRA_DIST += $(TESTS)
```
Note that I use `.lua` for the test extension rather than `busted`'s usual `.spec`.  Change according to taste (and change the name of the log compiler accordingly). You'll also probably want to change the Lua module search path passed to `-m` to suit your source code layout.
